name: Validate & Index
on:
  pull_request_target:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Validate frontmatter
        run: python scripts/validate_frontmatter.py
      - name: Build week indexes
        run: python scripts/build_index.py
      - name: Fail if index changes not committed
        run: |
          if ! git diff --quiet --exit-code; then
            echo "::error::Index tables changed. Please run scripts/build_index.py and commit the updates."
            git --no-pager diff
            exit 1
          fi
